import type { TopicSelfTests } from "./types";

export const selfTestData: TopicSelfTests[] = [
  {
    topicSlug: "api-assertion",
    questions: [
      {
        id: "api-assertion-1",
        topicSlug: "api-assertion",
        question: "接口断言只校验 HTTP 状态码 200 是否足够？",
        options: [
          "足够，200 表示请求成功",
          "不够，还需要校验响应体字段和业务副作用",
          "足够，其他校验是多余的",
          "看情况，有时足够有时不够",
        ],
        correctIndex: 1,
        explanation: "HTTP 200 只表示请求到达服务器并返回成功，不代表业务逻辑正确。真正的断言要覆盖响应体字段、数据库状态、消息投递等多层副作用。",
      },
      {
        id: "api-assertion-2",
        topicSlug: "api-assertion",
        question: "断言分层设计中，'链路断言'主要校验什么？",
        options: [
          "HTTP 状态码和响应结构",
          "响应体字段值",
          "数据库状态、缓存、消息投递等副作用",
          "接口响应时间",
        ],
        correctIndex: 2,
        explanation: "链路断言校验数据库状态、缓存一致性、消息队列投递、外部调用记录等跨系统的副作用，是断言分层的第三层。",
      },
      {
        id: "api-assertion-3",
        topicSlug: "api-assertion",
        question: "遇到响应结构经常变化时，如何保证断言稳定？",
        options: [
          "每次变化都修改断言代码",
          "只断言关键业务字段，用字段路径访问",
          "不做断言，只检查状态码",
          "使用固定数组下标访问字段",
        ],
        correctIndex: 1,
        explanation: "只断言关键业务字段、使用字段路径（如 JSONPath）而非固定位置、用 schema 校验替代字段逐个断言，可以让断言与具体结构解耦。",
      },
    ],
  },
  {
    topicSlug: "idempotency",
    questions: [
      {
        id: "idempotency-1",
        topicSlug: "idempotency",
        question: "支付回调为什么必须做幂等？",
        options: [
          "为了提高性能",
          "防止网络重试导致重复扣款或发货",
          "满足审计要求",
          "简化代码逻辑",
        ],
        correctIndex: 1,
        explanation: "支付网关发送回调后，如果没收到确认响应会自动重试。如果回调不做幂等，重复回调会导致重复扣款、重复发货，造成资损。",
      },
      {
        id: "idempotency-2",
        topicSlug: "idempotency",
        question: "以下哪个最适合作为幂等键？",
        options: [
          "用户 ID",
          "订单号或支付流水号",
          "当前时间戳",
          "随机字符串",
        ],
        correctIndex: 1,
        explanation: "幂等键需要具备业务唯一性和跨系统一致性。订单号、支付流水号是业务生成的全局唯一标识，天然适合做幂等键。",
      },
      {
        id: "idempotency-3",
        topicSlug: "idempotency",
        question: "消息重复消费的测试，主要验证什么？",
        options: [
          "消息能否被消费",
          "消息消费速度",
          "重复消费时数据不重复写入、状态不重复变更",
          "消息格式是否正确",
        ],
        correctIndex: 2,
        explanation: "消息幂等测试核心是验证重复消费时副作用是否可控：数据库记录不重复、状态不重复变更、外部调用只发生一次。",
      },
    ],
  },
  {
    topicSlug: "fixture",
    questions: [
      {
        id: "fixture-1",
        topicSlug: "fixture",
        question: "Pytest 中 session 级和 function 级 Fixture 的主要区别是什么？",
        options: [
          "session 级更快，function 级更慢",
          "session 级整个测试会话只初始化一次，function 级每个测试都初始化",
          "session 级只能用于数据库，function 级通用",
          "没有区别，只是名称不同",
        ],
        correctIndex: 1,
        explanation: "session 级 Fixture 整个测试会话只初始化一次，适合高成本的共享资源；function 级每个测试都重新初始化，适合需要隔离的测试数据。",
      },
      {
        id: "fixture-2",
        topicSlug: "fixture",
        question: "Fixture 嵌套过深会导致什么问题？",
        options: [
          "运行速度变快",
          "依赖关系难以追踪，阅读成本高",
          "测试结果更准确",
          "内存占用减少",
        ],
        correctIndex: 1,
        explanation: "Fixture 嵌套层级过多会让依赖关系难以追踪，代码阅读和维护成本高。建议控制嵌套深度在 2-3 层。",
      },
      {
        id: "fixture-3",
        topicSlug: "fixture",
        question: "Fixture 应该专注于什么？",
        options: [
          "复杂的业务逻辑处理",
          "环境准备和资源管理",
          "测试结果断言",
          "测试报告生成",
        ],
        correctIndex: 1,
        explanation: "Fixture 应专注于环境准备和资源管理（如登录态、数据库连接、浏览器实例），不混入业务逻辑，业务数据准备放在测试代码或 helper 函数中。",
      },
    ],
  },
  {
    topicSlug: "smoke-testing",
    questions: [
      {
        id: "smoke-1",
        topicSlug: "smoke-testing",
        question: "冒烟测试的主要目的是什么？",
        options: [
          "发现所有 Bug",
          "验证基本功能可用，快速判断版本是否可测",
          "测试性能指标",
          "测试安全性",
        ],
        correctIndex: 1,
        explanation: "冒烟测试的目的是快速验证基本功能是否可用，判断版本是否具备可测性，而不是发现所有 Bug。它是发布前的第一道门槛。",
      },
      {
        id: "smoke-2",
        topicSlug: "smoke-testing",
        question: "冒烟测试用例应该覆盖什么？",
        options: [
          "所有功能点",
          "核心业务主流程和关键路径",
          "边缘场景和异常情况",
          "UI 样式细节",
        ],
        correctIndex: 1,
        explanation: "冒烟测试用例应覆盖核心业务主流程和关键路径，如登录、下单、支付等主流程，不追求覆盖所有功能点。",
      },
    ],
  },
  {
    topicSlug: "regression-testing",
    questions: [
      {
        id: "regression-1",
        topicSlug: "regression-testing",
        question: "回归测试的主要目的是什么？",
        options: [
          "测试新功能",
          "验证修改后的代码没有影响原有功能",
          "测试性能",
          "测试用户体验",
        ],
        correctIndex: 1,
        explanation: "回归测试的目的是验证代码修改后，原有功能仍然正常工作，确保新改动没有引入新的问题（回归 Bug）。",
      },
      {
        id: "regression-2",
        topicSlug: "regression-testing",
        question: "如何提高回归测试的效率？",
        options: [
          "每次都执行全部测试用例",
          "只测试新功能",
          "自动化测试 + 按风险选择测试范围",
          "减少测试用例数量",
        ],
        correctIndex: 2,
        explanation: "提高回归效率的方法包括：自动化测试覆盖高频场景、按风险选择回归范围（关联功能优先）、分层回归（核心流程全量、其他抽样）。",
      },
    ],
  },
  {
    topicSlug: "pytest",
    questions: [
      {
        id: "pytest-1",
        topicSlug: "pytest",
        question: "Pytest 相比 unittest 的核心优势是什么？",
        options: [
          "Pytest 运行速度更快",
          "Pytest 无需继承 TestCase 类，用普通函数和 assert 语句即可写测试",
          "Pytest 只支持 Python 3.x，unittest 支持 Python 2.x",
          "Pytest 有官方支持，unittest 是社区维护",
        ],
        correctIndex: 1,
        explanation: "Pytest 的核心理念是「简单优先」，不需要继承任何基类，普通的 assert 语句就能自动生成详细的失败报告。相比 unittest，代码量通常减少 30%-50%，可读性更高。",
      },
      {
        id: "pytest-2",
        topicSlug: "pytest",
        question: "测试用例需要覆盖多组参数组合时，应该用什么方式实现？",
        options: [
          "写多个测试函数，每个函数测一组参数",
          "在测试函数内部用 for 循环遍历参数",
          "使用 @pytest.mark.parametrize 装饰器实现参数化",
          "使用 unittest 的 subTest 机制",
        ],
        correctIndex: 2,
        explanation: "@pytest.mark.parametrize 是 Pytest 内置的参数化机制，一行代码就能生成多组用例，每组参数独立执行、独立报告结果。相比 for 循环，参数化用例失败时能定位到具体哪组参数出错。",
      },
      {
        id: "pytest-3",
        topicSlug: "pytest",
        question: "conftest.py 文件应该放在什么位置？它的作用是什么？",
        options: [
          "放在项目根目录，只用于配置 pytest.ini",
          "放在 tests 目录下，用于定义共享 Fixture，子目录可自动继承",
          "放在任意位置，用命令行参数指定路径",
          "放在每个测试文件同级目录，只对当前文件生效",
        ],
        correctIndex: 1,
        explanation: "conftest.py 放在 tests 目录下，定义的 Fixture 对该目录及子目录下的所有测试生效，无需显式导入。这是 Pytest 的共享机制，适合存放登录态、数据库连接等公共资源初始化。",
      },
    ],
  },
  {
    topicSlug: "playwright",
    questions: [
      {
        id: "playwright-1",
        topicSlug: "playwright",
        question: "Playwright 相比 Selenium 的核心优势是什么？",
        options: [
          "Playwright 支持更多浏览器类型",
          "Playwright 内置自动等待机制，元素可操作时才执行，无需手动处理等待",
          "Playwright 是 Google 开发的，更权威",
          "Playwright 只支持 JavaScript，学习成本更低",
        ],
        correctIndex: 1,
        explanation: "Playwright 内置自动等待解决了 UI 自动化最头疼的元素不稳定问题，减少 80% 以上的显式等待代码。它直接与浏览器通信而非依赖 WebDriver 协议，因此更快更稳定。",
      },
      {
        id: "playwright-2",
        topicSlug: "playwright",
        question: "Page Object 模式中，方法命名应该遵循什么原则？",
        options: [
          "用底层操作命名，如 fillUsername()、clickButton()",
          "用业务动作命名，如 login()、addToCart()、checkout()",
          "用 CSS 选择器命名，如 clickSubmitBtn()",
          "用测试用例编号命名，如 step1()、step2()",
        ],
        correctIndex: 1,
        explanation: "Page Object 的方法是业务动作而非底层操作，用 login() 而不是 fillUsername() + fillPassword()。这样测试用例只关心业务流程，不关心实现细节，选择器变化只需修改 Page Object 一处。",
      },
      {
        id: "playwright-3",
        topicSlug: "playwright",
        question: "处理异步场景（如文件上传后等待处理完成）时，推荐什么等待策略？",
        options: [
          "使用固定 sleep 等待足够长时间",
          "无限循环等待直到结果出现",
          "监听 API 响应（page.waitForResponse）或等待 UI 状态变化",
          "不做等待，直接断言结果",
        ],
        correctIndex: 2,
        explanation: "Playwright 的自动等待只覆盖元素可见可点击，业务层面的状态需要显式等待。推荐监听 API 响应（page.waitForResponse）或等待 UI 状态变化（进度条消失、成功提示出现），比 sleep 更稳定更快。",
      },
    ],
  },
  {
    topicSlug: "api-testing",
    questions: [
      {
        id: "api-testing-1",
        topicSlug: "api-testing",
        question: "接口断言只验证 HTTP 状态码 200 是否足够？",
        options: [
          "足够，200 表示业务成功",
          "不够，需要覆盖响应体字段、数据库状态等业务结果",
          "看情况，有时足够有时不够",
          "足够，状态码是接口测试的核心",
        ],
        correctIndex: 1,
        explanation: "HTTP 200 只代表请求到达服务器并被处理，不代表业务逻辑正确。真正的断言要分层：协议层（状态码、响应结构）、业务层（字段值、状态流转）、链路层（数据库、缓存、消息队列等副作用）。",
      },
      {
        id: "api-testing-2",
        topicSlug: "api-testing",
        question: "异步接口（如提交退款申请后异步处理）的测试应该怎么验证？",
        options: [
          "只验证同步响应返回成功即可",
          "验证同步响应后，轮询查询最终状态或监听回调通知",
          "不需要测试异步接口",
          "用 sleep 等待足够时间后直接断言",
        ],
        correctIndex: 1,
        explanation: "异步接口返回成功只代表「请求已接收」，不代表「处理已完成」。需要验证同步响应正确后，通过轮询查询或监听回调验证最终状态（数据库状态更新、通知发送等）。",
      },
      {
        id: "api-testing-3",
        topicSlug: "api-testing",
        question: "接口自动化项目应该采用什么分层结构？",
        options: [
          "全部代码写在一个文件，简单直接",
          "三层结构：接口层（封装请求）、业务层（封装业务逻辑）、用例层（测试流程）",
          "按功能模块分文件，不做层级区分",
          "只分测试文件和配置文件",
        ],
        correctIndex: 1,
        explanation: "推荐三层结构：接口层封装请求细节（路径、参数、鉴权）；业务层封装业务逻辑（登录、下单、支付）；用例层只写测试流程和断言。分层后维护更简单，接口变更只需修改接口层。",
      },
    ],
  },
  {
    topicSlug: "async-api-testing",
    questions: [
      {
        id: "async-api-testing-1",
        topicSlug: "async-api-testing",
        question: "异步接口测试的核心挑战是什么？",
        options: [
          "请求参数构造复杂",
          "无法立即验证最终结果，需要等待异步处理完成",
          "异步接口响应速度慢",
          "异步接口不支持自动化测试",
        ],
        correctIndex: 1,
        explanation: "异步接口的难点在于最终结果验证，不是发起调用。调用返回成功只代表请求已接收，需要设计等待策略（轮询、回调监听）验证业务是否正确处理、数据是否正确落库。",
      },
      {
        id: "async-api-testing-2",
        topicSlug: "async-api-testing",
        question: "回调接口测试应该覆盖哪些关键场景？",
        options: [
          "只测试正常回调场景",
          "正常回调、重复回调（幂等）、乱序回调、超时回调",
          "只测试回调参数是否正确",
          "只测试回调响应速度",
        ],
        correctIndex: 1,
        explanation: "回调测试要覆盖：正常回调验证参数解析和业务处理；重复回调验证幂等处理；乱序回调验证状态机正确推进；超时回调验证补偿机制。幂等是回调场景的核心质量要求。",
      },
      {
        id: "async-api-testing-3",
        topicSlug: "async-api-testing",
        question: "轮询等待策略应该如何设计超时和间隔？",
        options: [
          "固定间隔 1 秒，无限等待直到成功",
          "根据业务 SLA 设置最大等待时间，使用指数退避减少轮询开销",
          "间隔越短越好，提高检测速度",
          "等待时间越长越好，避免误判",
        ],
        correctIndex: 1,
        explanation: "超时设计要考虑业务 SLA：设置合理的最大等待时间（如 30 秒），超时后标记失败。轮询间隔采用指数退避（1s, 2s, 4s...），避免频繁查询对系统造成压力。",
      },
    ],
  },
  {
    topicSlug: "ci-cd",
    questions: [
      {
        id: "ci-cd-1",
        topicSlug: "ci-cd",
        question: "质量门禁的核心作用是什么？",
        options: [
          "提高测试执行速度",
          "在关键节点阻断有问题的代码，防止发布到生产环境",
          "生成漂亮的测试报告",
          "减少人工测试工作量",
        ],
        correctIndex: 1,
        explanation: "没有门禁的 CI 只是「好看的报告」，不能真正阻止有问题的代码上线。门禁设计三要素：触发条件（代码提交、合并请求、发布前）、检查项（测试通过率、覆盖率）、处理策略（阻断、警告、人工确认）。",
      },
      {
        id: "ci-cd-2",
        topicSlug: "ci-cd",
        question: "CI 流水线执行时间过长时，应该如何优化？",
        options: [
          "减少测试用例数量",
          "分层执行：快速反馈层（smoke）高频触发，全量回归层夜间触发",
          "只运行失败的用例",
          "不做优化，等待时间不重要",
        ],
        correctIndex: 1,
        explanation: "分层执行策略：快速反馈层（5-10 分钟）高频触发；完整回归层（30 分钟-1 小时）合并请求触发；全量验证层（2-4 小时）夜间定时执行。反馈越慢，问题修复成本越高。",
      },
      {
        id: "ci-cd-3",
        topicSlug: "ci-cd",
        question: "CI 失败时，如何区分环境问题和代码问题？",
        options: [
          "全部认为是代码问题，通知开发者修复",
          "分析失败特征：同一用例时好时坏可能是环境问题，断言失败是代码问题",
          "不做区分，直接重新执行",
          "全部认为是环境问题，等待自动恢复",
        ],
        correctIndex: 1,
        explanation: "区分技巧：同一用例在多次执行中时好时坏，大概率是环境问题；用例失败但开发环境能通过，可能是环境配置差异；失败时查看日志，如果报错是服务不可用或超时，是环境问题。",
      },
    ],
  },
  // ========== 场景类自测题（第四批）==========
  {
    topicSlug: "payment-callback",
    questions: [
      {
        id: "payment-callback-1",
        topicSlug: "payment-callback",
        question: "支付回调测试最重要的关注点是什么？",
        options: [
          "回调接口的响应速度",
          "幂等处理、签名验证、状态同步",
          "回调接口的代码风格",
          "回调接口的 UI 展示",
        ],
        correctIndex: 1,
        explanation: "支付回调测试重点关注：幂等处理防止重复扣款、签名验证防止伪造回调、状态同步确保订单状态准确流转。这是四段式回答框架的核心风险层内容。",
      },
      {
        id: "payment-callback-2",
        topicSlug: "payment-callback",
        question: "怎么验证重复回调不会重复发货？",
        options: [
          "只检查订单状态是否更新",
          "构造同一回调请求重复发送 3-5 次，验证订单状态只更新一次、履约消息只触发一次",
          "检查回调接口是否正常响应",
          "只验证签名是否正确",
        ],
        correctIndex: 1,
        explanation: "重复回调验证要覆盖：第一，订单状态只更新一次；第二，履约消息（发货通知、积分发放）只触发一次；第三，数据库层面检查发货记录、库存扣减是否重复。幂等键设计要覆盖业务主键（订单号）。",
      },
      {
        id: "payment-callback-3",
        topicSlug: "payment-callback",
        question: "支付回调状态机验证要覆盖哪些边界场景？",
        options: [
          "只测试正常状态流转",
          "非法跳转、并发状态变更、超时状态处理",
          "只测试支付成功场景",
          "只测试退款场景",
        ],
        correctIndex: 1,
        explanation: "状态机测试边界包括：第一，非法跳转（待支付直接到已发货）必须被拦截；第二，并发状态变更（同时收到支付成功和退款回调）必须串行处理；第三，超时状态（支付中状态超过阈值）要有超时查询机制。",
      },
    ],
  },
  {
    topicSlug: "flash-sale",
    questions: [
      {
        id: "flash-sale-1",
        topicSlug: "flash-sale",
        question: "高并发抢购场景测试的核心目标是什么？",
        options: [
          "验证系统响应速度",
          "确保高并发下库存准确、订单不超卖、系统稳定不宕机",
          "测试 UI 展示效果",
          "验证用户注册流程",
        ],
        correctIndex: 1,
        explanation: "秒杀测试的核心目标是确保高并发下库存准确、订单不超卖、用户体验可接受、系统稳定不宕机。这是四段式回答框架的目标层内容。",
      },
      {
        id: "flash-sale-2",
        topicSlug: "flash-sale",
        question: "怎么验证不会超卖？",
        options: [
          "只检查库存是否扣减",
          "构造并发请求数量远大于库存数量，验证最终订单数不超过库存且库存扣减一致",
          "只检查订单是否创建成功",
          "只测试单个用户抢购",
        ],
        correctIndex: 1,
        explanation: "超卖验证要构造并发请求数量远大于库存数量的场景，如库存 100 件发起 1000 个并发请求，验证最终订单数不超过库存，且 Redis 缓存库存和数据库库存一致，无重复订单。",
      },
      {
        id: "flash-sale-3",
        topicSlug: "flash-sale",
        question: "秒杀场景降级机制触发边界有哪些？",
        options: [
          "只在系统崩溃时触发",
          "缓存失效、数据库异常、第三方服务超时",
          "只在用户投诉时触发",
          "只在促销结束时触发",
        ],
        correctIndex: 1,
        explanation: "降级触发边界包括：缓存失效时直接返回「售罄」避免请求打到数据库；数据库异常时熔断保护核心服务不受影响；第三方服务超时时降级处理不影响主流程。测试要验证降级触发准确、用户提示友好。",
      },
    ],
  },
  {
    topicSlug: "login-auth",
    questions: [
      {
        id: "login-auth-1",
        topicSlug: "login-auth",
        question: "登录鉴权场景题应该从哪些层面组织答案？",
        options: [
          "只讲登录流程",
          "认证层、授权层、风控层、会话层四个层面",
          "只讲密码安全",
          "只讲第三方登录",
        ],
        correctIndex: 1,
        explanation: "登录鉴权场景题的标准回答框架包含四个层面：认证层（账号密码校验、验证码防刷、多因素认证）、授权层（接口权限校验、角色资源映射、越权访问测试）、风控层（暴力破解防护、异常设备识别）、会话层（token 管理、生命周期、登出失效）。",
      },
      {
        id: "login-auth-2",
        topicSlug: "login-auth",
        question: "token 失效和续期测试要覆盖哪些场景？",
        options: [
          "只测试正常登录",
          "正常续期流程、过期后访问、登出后访问、并发刷新冲突、跨端登录踢出",
          "只测试 token 格式",
          "只测试 token 存储",
        ],
        correctIndex: 1,
        explanation: "token 测试覆盖四类场景：一是正常续期流程，token 快过期时刷新接口能否正常返回新 token；二是过期后访问返回 401；三是登出后原 token 立即失效；四是并发刷新冲突，多个请求同时刷新时保证只有一个有效。还要测跨端登录踢出场景。",
      },
      {
        id: "login-auth-3",
        topicSlug: "login-auth",
        question: "后台系统权限矩阵测试要覆盖哪些边界？",
        options: [
          "只测试菜单可见性",
          "菜单权限、按钮权限、接口权限、数据权限四个层次",
          "只测试管理员权限",
          "只测试登录状态",
        ],
        correctIndex: 1,
        explanation: "权限测试分四层：菜单权限验证不同角色登录后可见菜单是否正确；按钮权限验证页面操作按钮是否按角色显隐；接口权限验证后端接口是否做权限校验避免绕过前端直接调用；数据权限验证同一角色不同用户只能访问自己权限范围内的数据。",
      },
    ],
  },
  {
    topicSlug: "recommendation-system-test",
    questions: [
      {
        id: "recommendation-system-test-1",
        topicSlug: "recommendation-system-test",
        question: "推荐系统测试与传统功能测试的本质区别是什么？",
        options: [
          "推荐系统测试更简单",
          "输出结果具有不确定性和个性化特征，测试验证需要从确定性断言转向概率性评估",
          "推荐系统不需要自动化测试",
          "推荐系统只需要测试性能",
        ],
        correctIndex: 1,
        explanation: "推荐系统测试与传统功能测试的本质区别在于：输出结果具有不确定性和个性化特征，同一用户在不同时间、不同上下文可能得到不同推荐，测试验证需要从确定性断言转向概率性评估。",
      },
      {
        id: "recommendation-system-test-2",
        topicSlug: "recommendation-system-test",
        question: "A/B 测试设计的关键要点是什么？",
        options: [
          "只需要对比新旧算法",
          "流量分配保证样本量和统计显著性、分流策略保证用户分组稳定、指标设计区分核心指标和护栏指标",
          "只需要测试点击率",
          "只需要运行一周时间",
        ],
        correctIndex: 1,
        explanation: "A/B 测试设计要点：流量分配要保证样本量和统计显著性；分流策略要保证用户分组稳定（同一用户始终在同一组）；指标设计要区分核心指标（点击率、转化率）和护栏指标（用户体验负面影响、投诉率）；实验周期要覆盖足够长的观察时间。",
      },
      {
        id: "recommendation-system-test-3",
        topicSlug: "recommendation-system-test",
        question: "冷启动场景测试要覆盖哪些边界？",
        options: [
          "只测试新用户",
          "用户冷启动、物品冷启动、系统冷启动三类场景",
          "只测试新商品",
          "只测试系统上线",
        ],
        correctIndex: 1,
        explanation: "冷启动场景分三类测试：用户冷启动——新用户无历史行为数据时的推荐策略验证；物品冷启动——新上架商品或内容无交互数据时的推荐测试；系统冷启动——整个推荐系统上线初期的测试。测试策略包括构造模拟冷启动数据、对比冷启动与正常用户的效果差异。",
      },
    ],
  },
  {
    topicSlug: "compatibility-testing",
    questions: [
      {
        id: "compatibility-testing-1",
        topicSlug: "compatibility-testing",
        question: "兼容性矩阵怎么设计？按什么标准确定测试环境？",
        options: [
          "测试所有可能的浏览器和设备",
          "收集用户数据分析环境分布，按占比排序，前 80% 用户覆盖的环境为核心测试环境",
          "只测试最新版本的浏览器",
          "只测试开发人员使用的设备",
        ],
        correctIndex: 1,
        explanation: "兼容性矩阵设计思路：第一，收集用户数据统计用户使用的浏览器、设备、系统版本分布；第二，按占比排序，通常前 80% 用户覆盖的环境为核心测试环境；第三，结合业务风险，支付流程涉及的浏览器权重更高；第四，考虑维护成本在覆盖率和成本之间找平衡。",
      },
      {
        id: "compatibility-testing-2",
        topicSlug: "compatibility-testing",
        question: "自动化兼容测试的核心策略是什么？",
        options: [
          "只做手工测试",
          "核心流程自动化覆盖、视觉回归测试发现 UI 差异、云测平台并行执行多环境测试",
          "只测试后端接口",
          "只测试单一浏览器",
        ],
        correctIndex: 1,
        explanation: "自动化兼容测试策略：第一，核心流程自动化，登录、下单、支付等核心链路每次发版前自动运行；第二，视觉回归测试，对关键页面截图比对发现布局错乱、样式差异；第三，云测平台并行，利用并发能力同时执行多环境测试缩短周期。",
      },
      {
        id: "compatibility-testing-3",
        topicSlug: "compatibility-testing",
        question: "兼容性问题太多时优先级怎么排？",
        options: [
          "按发现顺序排序",
          "按影响面和严重程度划分：P0 阻塞级（核心功能不可用、影响用户占比 >10%）立即修复",
          "按问题类型排序",
          "按修复难度排序",
        ],
        correctIndex: 1,
        explanation: "兼容性问题优先级模型：按影响面和严重程度两个维度划分。P0 阻塞级（核心功能不可用、影响用户占比 >10%）立即修复；P1 严重级（核心功能受限、影响用户占比 5%-10%）当前版本修复；P2 一般级（体验问题、影响用户占比 1%-5%）排期修复。用户数据是核心依据。",
      },
    ],
  },
  // ========== 项目类自测题（第三批）==========
  {
    topicSlug: "payment-project",
    questions: [
      {
        id: "payment-project-1",
        topicSlug: "payment-project",
        question: "讲支付项目时，如何展示测试深度？",
        options: [
          "只说做了多少测试用例",
          "从测试分层、场景覆盖、质量保障策略三个维度展开",
          "只展示自动化覆盖率",
          "只讲发现了多少 Bug",
        ],
        correctIndex: 1,
        explanation: "展示测试深度要从测试分层（单元/接口/端到端）、场景覆盖（正常/异常/边界）、质量保障策略（幂等/金额/状态机/对账）三个维度系统展开，体现对支付业务的深入理解。",
      },
      {
        id: "payment-project-2",
        topicSlug: "payment-project",
        question: "支付项目测试中，哪个是必须重点验证的核心风险点？",
        options: [
          "UI 界面样式",
          "页面加载速度",
          "幂等、金额精度、状态机、对账一致性",
          "文案拼写错误",
        ],
        correctIndex: 2,
        explanation: "支付项目的核心风险点是资金安全和状态一致性，必须重点验证幂等处理（防重复扣款）、金额精度（防计算误差）、状态机流转（防非法跳转）、对账一致性（防资金差错）。",
      },
      {
        id: "payment-project-3",
        topicSlug: "payment-project",
        question: "面试中讲支付项目，如何体现你的独特价值？",
        options: [
          "强调项目规模大、用的人多",
          "用具体数据讲成果：如回归时长缩短、对账自动化率、线上资损率下降",
          "只讲技术栈和工具使用",
          "强调加班多、工作量大",
        ],
        correctIndex: 1,
        explanation: "面试官更关注你的实际贡献和量化成果。用具体数据展示：核心回归从 3 小时缩到 25 分钟、对账自动化覆盖 95%、线上资金类故障从 5 笔/月降到 0，比空泛描述更有说服力。",
      },
    ],
  },
  {
    topicSlug: "ecommerce-project",
    questions: [
      {
        id: "ecommerce-project-1",
        topicSlug: "ecommerce-project",
        question: "讲电商项目时，应该围绕哪些核心业务流程展开？",
        options: [
          "只讲购物车功能",
          "商品浏览 → 下单支付 → 履约发货 → 售后退款的完整链路",
          "只讲搜索推荐算法",
          "只讲后台管理系统",
        ],
        correctIndex: 1,
        explanation: "电商项目要围绕完整业务链路展开：商品浏览与搜索、购物车/下单/库存锁定/支付、履约发货、售后退款与营销核销，体现你对业务全流程的理解，而不是只关注单一功能点。",
      },
      {
        id: "ecommerce-project-2",
        topicSlug: "ecommerce-project",
        question: "电商项目的核心风险点有哪些？",
        options: [
          "页面样式错乱",
          "库存与订单状态不一致、优惠叠加计算错误、高并发超卖",
          "用户头像显示异常",
          "搜索关键词高亮问题",
        ],
        correctIndex: 1,
        explanation: "电商项目的核心风险点包括：库存与订单状态不一致（超卖/少卖）、优惠叠加和价格计算错误（资损）、高并发活动下的超卖/重复下单/回调延迟，这些是直接影响营收的关键风险。",
      },
      {
        id: "ecommerce-project-3",
        topicSlug: "ecommerce-project",
        question: "面试讲电商项目时，如何展示你的测试策略思维？",
        options: [
          "只说做了功能测试和性能测试",
          "分层策略：核心链路接口回归 + 营销规则数据驱动 + 下单支付双重校验",
          "强调测试用例数量多",
          "只讲自动化工具使用",
        ],
        correctIndex: 1,
        explanation: "展示测试策略思维要体现分层覆盖：核心链路做接口回归保障主流程、营销和价格规则做数据驱动组合测试覆盖边界、下单支付链路增加日志与数据库双重校验保障资金安全。",
      },
    ],
  },
  {
    topicSlug: "finance-project",
    questions: [
      {
        id: "finance-project-1",
        topicSlug: "finance-project",
        question: "讲金融项目时，应该重点突出哪些能力？",
        options: [
          "页面交互体验优化",
          "对账能力、审批流程覆盖、合规校验和资金链路验证",
          "测试环境搭建能力",
          "测试文档编写能力",
        ],
        correctIndex: 1,
        explanation: "金融项目要重点体现对账、审批流、合规校验、资金链路验证四大能力。金融业务对资金安全和合规性要求极高，这些是面试官最关注的核心能力。",
      },
      {
        id: "finance-project-2",
        topicSlug: "finance-project",
        question: "金融项目测试中，资金类接口应该如何验证？",
        options: [
          "只校验接口返回状态码",
          "做数据库与日志双重校验，确保资金流水一致性",
          "只做功能测试即可",
          "交给开发自测",
        ],
        correctIndex: 1,
        explanation: "金融项目资金类接口必须做数据库与日志双重校验，验证余额变动、流水记录、账户状态三者一致性。资金安全无小事，单靠接口返回验证不够，必须追溯数据落库。",
      },
      {
        id: "finance-project-3",
        topicSlug: "finance-project",
        question: "面试中讲金融项目，如何体现你的风险意识？",
        options: [
          "强调测试用例设计得多么详细",
          "主动讲资金错账、审批绕过、合规风险的测试覆盖和线上防护措施",
          "只讲正常流程测试",
          "强调自己发现了很多 Bug",
        ],
        correctIndex: 1,
        explanation: "金融项目面试要主动展示风险意识：资金错账和重复入账的验证、审批流程绕过的测试覆盖、合规字段缺失和报送数据错误的校验，以及上线后的监控告警机制。",
      },
    ],
  },
  {
    topicSlug: "microservice-architecture-project",
    questions: [
      {
        id: "microservice-project-1",
        topicSlug: "microservice-architecture-project",
        question: "讲微服务项目时，应该围绕哪些核心能力展开？",
        options: [
          "只讲单个服务的功能测试",
          "服务拆分、链路追踪、依赖管理和故障传播控制",
          "只讲接口性能测试",
          "只讲容器化部署",
        ],
        correctIndex: 1,
        explanation: "微服务项目要围绕服务拆分后的测试挑战展开：链路追踪验证服务调用、依赖关系梳理和管理、故障传播和熔断降级，体现你对分布式系统复杂性的理解。",
      },
      {
        id: "microservice-project-2",
        topicSlug: "microservice-architecture-project",
        question: "微服务项目测试中，如何验证服务故障的容错能力？",
        options: [
          "只做正常流程测试",
          "通过故障注入验证熔断、降级和链路恢复机制",
          "等线上出问题再处理",
          "只关注接口返回正确",
        ],
        correctIndex: 1,
        explanation: "微服务架构下的容错能力验证需要通过故障注入：模拟单服务故障验证熔断机制、验证降级策略是否生效、验证链路恢复后的自愈能力，这是微服务测试的关键场景。",
      },
      {
        id: "microservice-project-3",
        topicSlug: "microservice-architecture-project",
        question: "面试中讲微服务项目，如何展示你的问题定位能力？",
        options: [
          "说遇到问题就重启服务",
          "讲如何通过链路追踪快速定位故障源头和传播路径",
          "强调日志写得多么详细",
          "说有问题就找开发排查",
        ],
        correctIndex: 1,
        explanation: "展示问题定位能力要讲链路追踪的实践：通过 SkyWalking/Jaeger 追踪请求在各服务的耗时、定位慢服务和故障点、分析故障传播路径，体现你在分布式环境下的问题诊断能力。",
      },
    ],
  },
  {
    topicSlug: "legacy-system-refactor-project",
    questions: [
      {
        id: "legacy-project-1",
        topicSlug: "legacy-system-refactor-project",
        question: "讲遗留系统改造项目时，应该重点突出什么能力？",
        options: [
          "只讲新系统的功能测试",
          "渐进式迁移策略、兼容性保障、回滚能力和数据同步验证",
          "强调加班赶进度",
          "只讲代码重构技巧",
        ],
        correctIndex: 1,
        explanation: "遗留系统改造项目的核心挑战是平稳过渡，要重点展示：渐进式迁移策略（灰度切换）、新旧系统兼容性保障、快速回滚能力、数据同步一致性验证，体现你对迁移风险的管控。",
      },
      {
        id: "legacy-project-2",
        topicSlug: "legacy-system-refactor-project",
        question: "遗留系统改造中，如何验证新旧系统功能一致性？",
        options: [
          "只测新系统功能即可",
          "做新旧系统功能对比和数据一致性验证，灰度切换比对结果",
          "靠用户反馈发现问题",
          "只看日志是否有报错",
        ],
        correctIndex: 1,
        explanation: "遗留系统改造要做新旧系统对比验证：相同请求并行调用新旧系统、比对返回结果和数据状态、发现差异及时修复，确保迁移过程中业务逻辑不丢失、不变形。",
      },
      {
        id: "legacy-project-3",
        topicSlug: "legacy-system-refactor-project",
        question: "面试中讲遗留系统改造，如何体现你的风险意识？",
        options: [
          "强调自己参与了整个迁移过程",
          "讲流量切换的灰度策略、回滚验证和遗留依赖识别",
          "只讲新系统用了什么新技术",
          "强调旧系统代码多么糟糕",
        ],
        correctIndex: 1,
        explanation: "遗留系统改造的风险意识体现在：流量切换做灰度验证（小流量→大流量）、回滚预案和验证充分性、遗留依赖的完整识别和兼容性处理，确保切换失败时能快速止损。",
      },
    ],
  },
  // ========== 术语类自测题（第一批）==========
  {
    topicSlug: "test-pyramid",
    questions: [
      {
        id: "test-pyramid-1",
        topicSlug: "test-pyramid",
        question: "测试金字塔主张各层测试的数量比例应该是？",
        options: [
          "单元测试最少、集成测试适中、端到端测试最多",
          "单元测试最多、集成测试适中、端到端测试最少",
          "三层测试数量相同",
          "根据项目随意分配，没有固定比例",
        ],
        correctIndex: 1,
        explanation: "测试金字塔的核心原则是底层单元测试数量最多（成本低、反馈快），中间集成测试适中（覆盖模块交互），顶层端到端测试最少（成本高、维护难）。这种结构确保整体测试体系既高效又全面，避免倒金字塔的高成本低效率问题。",
      },
      {
        id: "test-pyramid-2",
        topicSlug: "test-pyramid",
        question: "项目发现「倒金字塔」现象（80% UI 测试、10% 单元测试），应该怎么调整？",
        options: [
          "保持现状，UI 测试更能发现用户问题",
          "一次性删除所有 UI 测试，只保留单元测试",
          "先补齐单元测试覆盖核心模块，再精简 UI 测试只保留核心流程",
          "增加更多 UI 测试提高覆盖",
        ],
        correctIndex: 2,
        explanation: "倒金字塔调整需要分步走：第一步补齐单元测试，优先覆盖核心业务模块（订单、支付、用户）；第二步精简 UI 测试，只保留核心业务流程；第三步加强集成测试，覆盖模块间交互。不能一次性删除所有 UI 测试，也不能保持现状。调整后整体覆盖率不能下降。",
      },
      {
        id: "test-pyramid-3",
        topicSlug: "test-pyramid",
        question: "单元测试和集成测试的边界怎么划分？",
        options: [
          "单元测试测试小功能，集成测试测试大功能",
          "单元测试不涉及外部依赖（用 Mock），集成测试涉及真实外部依赖",
          "单元测试执行快，集成测试执行慢",
          "单元测试是开发写的，集成测试是测试写的",
        ],
        correctIndex: 1,
        explanation: "单元测试和集成测试的核心区别是「是否涉及真实外部依赖」。单元测试只测试单个函数或类，外部依赖（数据库、网络、第三方服务）用 Mock 或 Stub 替代；集成测试测试多模块协作，外部依赖用真实环境。不是按功能大小、执行速度或编写角色划分。",
      },
    ],
  },
  {
    topicSlug: "test-coverage",
    questions: [
      {
        id: "test-coverage-1",
        topicSlug: "test-coverage",
        question: "代码覆盖率高就说明测试质量好吗？",
        options: [
          "是的，覆盖率越高测试质量越好",
          "不一定，覆盖率只反映代码被执行，不反映执行结果被有效验证",
          "覆盖率 80% 以上才算测试质量好",
          "覆盖率与测试质量无关",
        ],
        correctIndex: 1,
        explanation: "代码覆盖率只反映「代码路径被执行」，不反映「执行结果被验证」。测试可能覆盖了代码路径但没有有效断言，或者只测试了正常场景没有测试边界场景。覆盖率是参考指标，不是质量指标，要配合「有效断言」「深度测试」「关键路径覆盖」才有意义。",
      },
      {
        id: "test-coverage-2",
        topicSlug: "test-coverage",
        question: "如何设定合理的覆盖率目标？",
        options: [
          "所有模块统一设定 100% 覆盖率目标",
          "核心业务模块高覆盖（80%+），次要模块适度覆盖（50%+），按风险分级设定",
          "追求越高越好，覆盖率目标没有上限",
          "覆盖率目标不重要，测试数量更重要",
        ],
        correctIndex: 1,
        explanation: "覆盖率目标的设定原则是「按风险分级设定」，不是一刀切。核心业务模块（支付、订单、用户）风险高，设定高覆盖率目标（80%+ 或 90%+）；次要模块风险中等，设定中等目标（50%+）；边缘功能风险低，设定低目标或不强制要求。投入产出比合理，关键路径全覆盖比全部路径高覆盖更有价值。",
      },
      {
        id: "test-coverage-3",
        topicSlug: "test-coverage",
        question: "完整的覆盖率体系应该包含哪些维度？",
        options: [
          "只需要代码覆盖率即可",
          "代码覆盖率 + 功能覆盖率 + 场景覆盖率三个维度",
          "只需要功能覆盖率即可",
          "只需要测试用例数量",
        ],
        correctIndex: 1,
        explanation: "完整的覆盖率体系需要三个维度结合：代码覆盖率（代码执行路径覆盖）、功能覆盖率（需求/功能点覆盖比例）、场景覆盖率（业务流程/用户路径覆盖比例）。代码覆盖率最容易统计但意义有限，功能覆盖率和场景覆盖率更能反映业务覆盖程度。三者结合才能完整衡量测试覆盖。",
      },
    ],
  },
  {
    topicSlug: "boundary-value-analysis",
    questions: [
      {
        id: "boundary-value-1",
        topicSlug: "boundary-value-analysis",
        question: "边界值分析的「三值原则」指的是测试哪些值？",
        options: [
          "只测试边界值本身",
          "边界值、边界-1、边界+1 三个点",
          "最小值、中间值、最大值",
          "任意三个测试值",
        ],
        correctIndex: 1,
        explanation: "边界值分析不只是测边界本身，要测「边界值、边界-1、边界+1」三个点。比如输入长度限制 1-100，测试点包括 0（边界-1，非法）、1（边界，最小合法）、100（边界，最大合法）、101（边界+1，非法）。很多缺陷发生在边界附近而非边界本身。",
      },
      {
        id: "boundary-value-2",
        topicSlug: "boundary-value-analysis",
        question: "支付活动「满 100 减 10」，用户输入 99.99 元时优惠没生效，这是什么问题？",
        options: [
          "功能逻辑错误，与边界值无关",
          "边界值处理错误，开发判断条件只考虑整数没考虑小数边界",
          "性能问题，系统处理太慢",
          "界面显示问题",
        ],
        correctIndex: 1,
        explanation: "这是典型的边界值问题。开发设计优惠规则时用整数比较（金额 >= 100），没考虑金额可以是小数（99.99 不是整数）。边界值分析应该测试 99.99（小于 100）、100.00（等于 100）、100.01（大于 100）三个点，但开发只测试了 100 这个点，漏了 99.99 这种接近边界的值。",
      },
      {
        id: "boundary-value-3",
        topicSlug: "boundary-value-analysis",
        question: "边界值分析与等价类划分怎么配合使用？",
        options: [
          "两者是替代关系，选一种即可",
          "等价类划分划定测试范围，边界值分析在边界附近深入测试",
          "先用边界值分析，再做等价类划分",
          "两者各自独立使用，不需要配合",
        ],
        correctIndex: 1,
        explanation: "等价类划分和边界值分析是配合关系而非替代关系。先用等价类划分确定测试范围（每个等价类至少测一个代表值），再用边界值分析在边界附近深入测试（边界-1、边界、边界+1）。等价类划分减少用例数量，边界值分析提高关键区域覆盖。两者配合既能全面又能精简。",
      },
    ],
  },
  {
    topicSlug: "equivalence-class-partition",
    questions: [
      {
        id: "equivalence-class-1",
        topicSlug: "equivalence-class-partition",
        question: "等价类划分的核心假设是什么？",
        options: [
          "所有输入值测试结果都相同",
          "等价类内的所有值对于测试目的来说是等效的，测试一个代表值即可代表该类",
          "输入值数量有限，可以穷举测试",
          "测试结果与输入值无关",
        ],
        correctIndex: 1,
        explanation: "等价类划分的核心假设是「等价类内所有值对于测试目的来说是等效的」，测试时只需从每个等价类中选取一个代表值进行测试，假设该等价类中的其他值会得到相同的测试结果。这个假设能大幅减少测试用例数量，但关键等价类要用多个值验证假设是否成立。",
      },
      {
        id: "equivalence-class-2",
        topicSlug: "equivalence-class-partition",
        question: "用户名长度限制 6-20 位字母数字，无效等价类应该怎么划分？",
        options: [
          "只有一个无效等价类：所有不符合规则的输入",
          "多种非法情况各为独立无效等价类：长度 < 6、长度 > 20、含特殊字符、空值",
          "无效等价类不重要，只测有效等价类即可",
          "按输入值大小划分无效等价类",
        ],
        correctIndex: 1,
        explanation: "无效等价类划分要覆盖所有非法情况，每种非法情况独立一类：长度小于 6 是一类、长度大于 20 是一类、含特殊字符是一类、空值是一类。每种非法情况要单独设计测试用例，保证只测试一种非法情况，其他输入保持有效，这样才能准确定位问题。",
      },
      {
        id: "equivalence-class-3",
        topicSlug: "equivalence-class-partition",
        question: "有效等价类和无效等价类设计测试用例的原则有什么不同？",
        options: [
          "两者设计原则相同，都是单独测试",
          "有效等价类可以组合测试（一个用例覆盖多个有效类），无效等价类必须单独测试",
          "无效等价类可以组合测试，有效等价类必须单独测试",
          "两者都可以组合测试",
        ],
        correctIndex: 1,
        explanation: "有效等价类可以组合成一个有效用例（一个用例覆盖多个有效等价类，所有输入都是有效值），无效等价类必须单独测试（每个无效等价类一个用例，其他输入保持有效值）。如果一个用例同时测试多个无效等价类，无法定位具体是哪个非法输入导致的问题。",
      },
    ],
  },
  {
    topicSlug: "page-object-pattern",
    questions: [
      {
        id: "page-object-1",
        topicSlug: "page-object-pattern",
        question: "页面对象模式的核心思想是什么？",
        options: [
          "把测试用例写在页面类里",
          "把每个页面抽象成一个类，封装元素定位和操作，让测试代码与页面结构解耦",
          "用页面截图代替测试代码",
          "把所有页面合并成一个类",
        ],
        correctIndex: 1,
        explanation: "页面对象模式的核心思想是把每个页面抽象成一个类，封装该页面的元素定位、操作方法和业务逻辑。测试代码只调用页面对象的方法，不直接操作元素。当页面结构变化时，只需修改页面对象类，测试代码不受影响，大大降低维护成本。",
      },
      {
        id: "page-object-2",
        topicSlug: "page-object-pattern",
        question: "页面对象里应该包含断言吗？",
        options: [
          "应该包含，断言是测试的核心",
          "不应该包含，页面对象只负责「动作」，断言应该放在测试代码里",
          "部分断言可以放在页面对象",
          "看情况决定",
        ],
        correctIndex: 1,
        explanation: "页面对象不应该包含断言。页面对象只负责「动作」（元素定位和操作），测试代码负责「验证」（断言）。如果在页面对象里写断言，会导致职责混乱、测试逻辑分散。职责分离让代码清晰、维护简单。页面对象只返回数据供测试代码断言。",
      },
      {
        id: "page-object-3",
        topicSlug: "page-object-pattern",
        question: "如何降低页面对象与页面结构的耦合，减少维护成本？",
        options: [
          "使用 xpath 绝对定位，精确匹配元素位置",
          "使用稳定的选择器策略（优先 data-testid，其次语义化标签），定位器集中管理",
          "不使用选择器，直接操作页面",
          "每次页面变化都重写所有测试代码",
        ],
        correctIndex: 1,
        explanation: "降低维护成本的策略是「稳定选择器」「定位器集中管理」。优先用 data-testid 属性（开发专门为测试添加的稳定属性），其次用语义化标签，避免依赖易变的 xpath。定位器定义在类开头，方便统一查看和修改。要求开发为关键元素添加 data-testid，元素位置变化不影响定位。",
      },
    ],
  },
];

export function getSelfTestsForTopic(slug: string): TopicSelfTests | undefined {
  return selfTestData.find((t) => t.topicSlug === slug);
}
